---
# Standard-System-Pakete für jedes Debian-basierte System
common_base_packages:
  - sudo
  - curl
  - wget
  - git
  - htop
  - python3
  - iperf3

# Standard-Shell für neue User
common_default_shell: /bin/bash
