---
host_services:
  - name: cloudflared-a
    upstream: "{{ ansible_host }}:{{ cloudflared_metrics_port }}"
    exposure: intern
    gatus_group: proxmox
    health_url: "http://{{ ansible_host }}:{{ cloudflared_metrics_port }}/ready"
