---
host_services:
  - name: gatus
    upstream: "{{ ansible_host }}:{{ gatus_web_port }}"
    exposure: intern
    gatus_group: proxmox
    gatus_host: wyse-3040
    health_url: "http://{{ ansible_host }}:{{ gatus_web_port }}/health"

gatus_storage_type: sqlite
gatus_discord_webhook: "{{ vault_discord_webhook }}"
gatus_failure_threshold: 2

gatus_alerting:
  discord:
    webhook-url: "${DISCORD_WEBHOOK}"

gatus_endpoints:
  - name: udr-gui
    group: infrastructure
    url: "https://172.16.0.1/"
    interval: 1m
    client:
      insecure: true
      timeout: 10s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: pve-alderaan-api
    group: infrastructure
    url: "https://{{ hostvars['pve-node01'].ansible_host }}:8006"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 240h"
    client:
      insecure: true
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: pve-corellia-api
    url: "https://{{ hostvars['pve-node02'].ansible_host }}:8006"
    group: infrastructure
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 240h"
    client:
      insecure: true
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: unraid-nas
    url: "http://{{ hostvars['unraid-nas'].ansible_host }}"
    group: infrastructure
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    client:
      insecure: true
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: mosquitto
    url: "tcp://{{ hostvars['lxc-mosquitto'].ansible_host }}:1883"
    group: proxmox
    interval: 1m
    conditions: ["[CONNECTED] == true"]
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: npm
    url: "http://172.16.10.208:81/api"
    group: proxmox
    interval: 1m
    conditions:
    - "[CONNECTED] == true"
    - "[BODY].status == OK"
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: pihole-hoth
    url: "{{ hostvars['rpi-dns'].ansible_host }}"
    group: DNS
    interval: 1m
    dns:
      query-name: "cloudflare.com"
      query-type: "A"
    conditions: 
      - "[DNS_RCODE] == NOERROR"
      - "[BODY] != 0.0.0.0"
    alerts:
    - type: discord
      failure-threshold: 3
      send-on-resolved: true

  - name: pihole-mustafar
    url: "{{ hostvars['wyse-3040'].ansible_host }}"
    group: DNS
    interval: 1m
    dns:
      query-name: "cloudflare.com"
      query-type: "A"
    conditions: 
      - "[DNS_RCODE] == NOERROR"
      - "[BODY] != 0.0.0.0"
    alerts:
    - type: discord
      failure-threshold: 3
      send-on-resolved: true

gatus_maintenance:
  every: ["Monday"]
  start: "03:55"
  duration: "2h10m"
  timezone: "{{ timezone }}"