---
host_services:
  - name: cloudflared-a
    exposure: none
    gatus_group: proxmox
    gatus_conditions: ["[STATUS] == 200", "[BODY].readyConnections > 0"]
    health_url: "http://{{ ansible_host }}:{{ cloudflared_metrics_port }}/ready"
