---
host_services:
  - name: sonarr
    upstream: "{{ ansible_host }}:8989"
    exposure: intern
    gatus_group: unraid
    gatus_conditions: ["[STATUS] == 200", "[BODY].status == OK"]
    health_url: "http://{{ ansible_host }}:8989/ping"
