---
gatus_storage_type: memory
gatus_deployment: container
gatus_discord_webhook: "{{ vault_discord_critical_webhook }}"
gatus_failure_threshold: 2
gatus_failure_critical_threshold: 1

gatus_alerting:
  discord:
    webhook-url: "${DISCORD_WEBHOOK}"

gatus_external_endpoints:
  - name: appdata
    group: backups
    token: "${GATUS_HEARTBEAT_TOKEN}"
    heartbeat:
      interval: 169h
    alerts:
      - type: discord
        failure-threshold: "{{ gatus_failure_critical_threshold }}"
        send-on-resolved: true

  - name: home_assistant
    group: backups
    token: "${GATUS_HEARTBEAT_TOKEN}"
    heartbeat:
      interval: 25h
    alerts:
      - type: discord
        failure-threshold: "{{ gatus_failure_critical_threshold }}"
        send-on-resolved: true

  - name: klipper
    group: backups
    token: "${GATUS_HEARTBEAT_TOKEN}"
    heartbeat:
      interval: 169h
    alerts:
      - type: discord
        failure-threshold: "{{ gatus_failure_critical_threshold }}"
        send-on-resolved: true

  - name: nightly
    group: backups
    token: "${GATUS_HEARTBEAT_TOKEN}"
    heartbeat:
      interval: 25h
    alerts:
      - type: discord
        failure-threshold: "{{ gatus_failure_critical_threshold }}"
        send-on-resolved: true

  - name: paperless
    group: backups
    token: "${GATUS_HEARTBEAT_TOKEN}"
    heartbeat:
      interval: 25h
    alerts:
      - type: discord
        failure-threshold: "{{ gatus_failure_critical_threshold }}"
        send-on-resolved: true

  - name: vaultwarden
    group: backups
    token: "${GATUS_HEARTBEAT_TOKEN}"
    heartbeat:
      interval: 25h
    alerts:
      - type: discord
        failure-threshold: "{{ gatus_failure_critical_threshold }}"
        send-on-resolved: true

  - name: vzdump_lxc
    group: backups
    token: "${GATUS_HEARTBEAT_TOKEN}"
    heartbeat:
      interval: 25h
    alerts:
      - type: discord
        failure-threshold: "{{ gatus_failure_critical_threshold }}"
        send-on-resolved: true

  - name: zigbee2mqtt
    group: backups
    token: "${GATUS_HEARTBEAT_TOKEN}"
    heartbeat:
      interval: 169h
    alerts:
      - type: discord
        failure-threshold: "{{ gatus_failure_critical_threshold }}"
        send-on-resolved: true

gatus_endpoints:
  - name: pve-alderaan-api
    group: infrastructure
    url: "https://{{ hostvars['pve-node01'].ansible_host }}:8006"
    interval: 5m
    conditions: ["[STATUS] == 200"]
    client:
      insecure: true
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: pve-corellia-api
    url: "https://{{ hostvars['pve-node02'].ansible_host }}:8006"
    group: infrastructure
    interval: 5m
    conditions: ["[STATUS] == 200"]
    client:
      insecure: true
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: unraid
    url: "tcp://{{ hostvars['unraid-nas'].ansible_host }}:80"
    group: infrastructure
    interval: 5m
    conditions: ["[CONNECTED] == true"]
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: home-assistant
    url: "tcp://{{ hostvars['vm-hassio'].ansible_host }}:8123"
    group: infrastructure
    interval: 5m
    conditions: ["[CONNECTED] == true"]
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: wan
    url: "tcp://1.1.1.1:443"
    group: infrastructure
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      - "[RESPONSE_TIME] < 500"    
    alerts:
    - type: discord
      failure-threshold: "{{ gatus_failure_threshold }}"
      send-on-resolved: true

  - name: pihole-hoth
    url: "{{ hostvars['rpi-dns'].ansible_host }}"
    group: infrastructure
    interval: 1m
    dns:
      query-name: "cloudflare.com"
      query-type: "A"
    conditions: 
      - "[DNS_RCODE] == NOERROR"
      - "[BODY] != 0.0.0.0"
    alerts:
    - type: discord
      failure-threshold: 3
      send-on-resolved: true

pihole_max_db_days: 7
