---
proxmox_nodes:
  hosts:
    pve-node01:
      ansible_host: 172.16.10.10
    pve-node02:
      ansible_host: 172.16.10.50
  vars:
    ansible_user: root
# WICHTIG: Nutze am besten SSH-Keys. Falls du Passwörter nutzt, 
# führe ansible-playbook mit --ask-pass aus.
