---
# =============================================================================
# 1. KONKRETE HOST-GRUPPEN (Physikalische Hardware & Virtuelle Maschinen)
# =============================================================================

proxmox_nodes:
  hosts:
    pve-node01:
      ansible_host: 172.16.10.10
      system_hostname: "Alderaan"
    pve-node02:
      ansible_host: 172.16.10.50
      system_hostname: "Corellia"

storage_nodes:
  hosts:
    unraid-nas:
      ansible_host: 172.16.10.20
      system_hostname: "Coruscant"

single_board_computers:
  hosts:
    rpi-dns:
      ansible_host: 172.16.10.40
      system_hostname: "Hoth"
    rpi-klipper:
      ansible_host: 172.16.50.30
      system_hostname: "Kamino"

thin_clients:
  hosts:
    wyse-3040:
      ansible_host: 172.16.10.60
      system_hostname: "Mustafar"

# Proxmox VMs (QEMU)
qemu_vms:
  hosts:
    vm-hassio:
      ansible_host: 172.16.10.11

# Proxmox Container (LXC)
lxc_containers:
  hosts:
    lxc-mosquitto:
      ansible_host: 172.16.10.201
    lxc-zigbee2mqtt:
      ansible_host: 172.16.10.202
      system_hostname: zigbee2mqtt-slzb06
      container_role: zigbee2mqtt
      container_cores: 1
      container_memory: 512
      container_disk: 4
      container_mac: "BC:24:11:4D:E8:02"
    lxc-pihole:
      ansible_host: 172.16.10.203
    lxc-uptimekuma:
      ansible_host: 172.16.10.204
    lxc-vaultwarden:
      ansible_host: 172.16.10.205
    lxc-paperless:
      ansible_host: 172.16.10.207
    lxc-nginx-proxy:
      ansible_host: 172.16.10.208
    lxc-victoriametrics:
      ansible_host: 172.16.10.209
    lxc-grafana:
      ansible_host: 172.16.10.210
    lxc-wattwarriors:
      ansible_host: 172.16.10.211
    lxc-cloudflared:
      ansible_host: 172.16.10.212
    lxc-authentik:
      ansible_host: 172.16.10.213

unifi_controllers:
  hosts:
    unifi-controller:
      ansible_host: 172.16.0.1 #oder besser 172.16.10.1?
      ansible_connection: local

unifi_hardware:
  hosts:
    usw-switch-office:
      ansible_host: 172.16.0.10
      system_hostname: "tbd"
    usw-switch-hallway:
      ansible_host: 172.16.0.20
      system_hostname: "tbd"
    usw-switch-media:
      ansible_host: 172.16.0.30
      system_hostname: "tbd"
    ap-u6-lr:
      ansible_host: 172.16.0.40
      system_hostname: "Jedha"

# =============================================================================
# 2. LOGISCHE OBERGRUPPEN (Verknüpfen Gruppen über 'children')
# =============================================================================

# Fasst alle echten, physischen Server zusammen:
bare_metal:
  children:
    proxmox_nodes:
    storage_nodes:
    single_board_computers:
    thin_clients:

# Fasst alle virtuellen Instanzen auf Proxmox zusammen:
virtual_machines:
  children:
    qemu_vms:
    lxc_containers:

# Fasst alle echten Netzwerkgeräte zusammen:
network_devices:
  children:
    unifi_controllers:
    unifi_hardware:

# =============================================================================
# 3. FUNKTIONALE LOGIK-GRUPPEN (Welches Gerät macht was?)
# =============================================================================

control_node:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

docker_hosts:
  hosts:
    unraid-nas:
    wyse-3040:

pve_qdevice:
  hosts:
    wyse-3040:
