proxmox_api_host: 172.16.10.10
proxmox_api_user: ansible@pve
proxmox_api_token_id: ansible-automation
proxmox_ansible_pubkey_path: ~/.ssh/id_ed25519_ansible.pub
proxmox_default_disk: 4
proxmox_default_cores: 1
proxmox_default_memory: 1024
proxmox_default_template: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
proxmox_default_gateway: 172.16.10.1
proxmox_default_pool: ansible-automation
proxmox_default_node: "Alderaan"
