---
# roles/proxmox_node/tasks/main.yml  – nur noch imports
- import_tasks: repos.yml
- import_tasks: upgrade.yml
- import_tasks: nag_banner.yml
- import_tasks: packages.yml
- import_tasks: storage.yml
