---
- name: systemd-Unit einspielen
  ansible.builtin.template:
    src: zigbee2mqtt.service.j2
    dest: /etc/systemd/system/zigbee2mqtt.service
  notify: zigbee2mqtt neu starten

- name: zigbee2mqtt aktivieren
  ansible.builtin.systemd:
    name: zigbee2mqtt
    state: started
    enabled: true
    daemon_reload: true
