---
# -----------------------------------------------------------------------------
# 1. HOSTNAME & LOCALES SETUP
# -----------------------------------------------------------------------------
- name: System-Hostnamen setzen (Star Wars Name oder Fallback auf Ansible-Name)
  ansible.builtin.hostname:
    name: "{{ system_hostname | default(inventory_hostname) }}"

- name: Hostnamen in /etc/hosts eintragen (127.0.1.1)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ system_hostname | default(inventory_hostname) }}"
    state: present

# -----------------------------------------------------------------------------
# 2. BASE PACKAGES
# -----------------------------------------------------------------------------
- name: Grundlegende Systempakete installieren
  ansible.builtin.apt:
    name: "{{ common_base_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Node Exporter Service aktivieren und starten
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: started
    enabled: true

# -----------------------------------------------------------------------------
# 3. ANSIBLE SERVICE-USER SETUP
# -----------------------------------------------------------------------------
- name: Gruppe 'ansible' anlegen
  ansible.builtin.group:
    name: ansible
    state: present

- name: Service-User 'ansible' anlegen
  ansible.builtin.user:
    name: ansible
    group: ansible
    groups: sudo
    append: true
    shell: "{{ common_default_shell }}"
    state: present
    create_home: true

- name: Sudoers-Eintrag für 'ansible' ohne Passworteingabe anlegen
  ansible.builtin.copy:
    content: "ansible ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'

- name: SSH-Public-Key dynamisch aus ansible.cfg hinterlegen
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', (ansible_private_key_file | expanduser) + '.pub') }}"
