---
# roles/common/tasks/main.yml  – nur noch imports
- import_tasks: hostname.yml
- import_tasks: packages.yml
- include_tasks: user.yml
  when: "'proxmox_nodes' not in group_names"
- import_tasks: resolv.yml