---
- name: Grundlegende Systempakete installieren
  ansible.builtin.apt:
    name: "{{ common_base_packages }}"
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Disable iperf3 and make sure it is masked
  ansible.builtin.systemd_service:
    name: iperf3
    masked: true
  