---
# First run should be done with parameters --ask-pass
- name: Proxmox SSH Hardening
  hosts: proxmox_nodes
  gather_facts: true
  become: true

  tasks:
    - name: SSH-Public-Key für Root hinterlegen
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519_ansible.pub') }}"

    - name: Passwort-Authentifizierung über SSH deaktivieren
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH

    - name: Root-Login nur mit SSH-Key erlauben
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
        state: present
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
