---
- name: Container erstellen
  hosts: lxc_provisioned
  gather_facts: false
  become: false
  roles:
    - proxmox_container

- name: Warten, bis SSH erreichbar ist
  hosts: lxc_provisioned
  gather_facts: false
  vars:
    ansible_user: root
  tasks:
    - name: Warten bis SSH erreichbar ist
      ansible.builtin.wait_for_connection:
        timeout: 60

- name: Container einrichten
  hosts: lxc_provisioned
  become: true
  vars:
    ansible_user: root
  roles:
    - common
    - hardening
  tasks:
    - name: Service-Rolle anwenden
      ansible.builtin.include_role:
        name: "{{ container_role }}"
