---
- name: Konfigurationsverzeichnis anlegen
  ansible.builtin.file:
    path: "{{ gatus_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Datenverzeichnis anlegen
  ansible.builtin.file:
    path: "{{ gatus_data_dir }}"
    state: directory
    owner: "{{ gatus_user }}"
    group: "{{ gatus_user }}"
    mode: "0755"
  when: gatus_storage_type == 'sqlite'
