cloudflared_ingress:
  - hostname: "paperless.{{ external_domain }}"
    service: "{{ cloudflared_default_origin }}"
  - hostname: "wattwarriors.{{ external_domain }}"
    service: "{{ cloudflared_default_origin }}"
  - hostname: "status.{{ external_domain }}"
    service: "{{ cloudflared_default_origin }}"
  - hostname: "auth.{{ external_domain }}"
    service: "{{ cloudflared_default_origin }}"
  - hostname: "immich.{{ external_domain }}"
    service: "{{ cloudflared_default_origin }}"
  - hostname: "seer.{{ external_domain }}"
    service: "{{ cloudflared_default_origin }}"
  - service: http_status:404
