---
unbound_private_domains:
  - "myunraid.net"
pihole_cname_records:
  - "ha.ledermann.cc,npm.lan"
  - "immich.ledermann.cc,npm.lan"
  - "jellyfin.ledermann.cc,npm.lan"
  - "paperless.ledermann.cc,npm.lan"
  - "z2m.lan,npm.lan"
  - "prowlarr.lan,npm.lan"
  - "sonarr.lan,npm.lan"
  - "radarr.lan,npm.lan"
  - "sabnzbd.lan,npm.lan"
  - "wattwarriors.ledermann.cc,npm.lan"
  - "vault.ledermann.cc,npm.lan"
  - "grafana.lan,npm.lan"
  - "uptimekuma.lan,npm.lan"
  - "victoriametrics.lan,npm.lan"
  - "seer.ledermann.cc,npm.lan"
  - "status.ledermann.cc,npm.lan"
  - "maintainerr.lan,npm.lan"
  - "auth.ledermann.cc,npm.lan"
  - "bazarr.lan,npm.lan"
  - "alderaan.ledermann.cc,npm.lan"
  - "corellia.ledermann.cc,npm.lan"
pihole_dns_hosts:
  - "172.16.10.20 unraid.lan"
  - "172.16.10.1 unifi.lan"
  - "172.16.10.40 pihole1.lan"
  - "172.16.10.203 pihole2.lan"
  - "172.16.10.208 npm.lan"
  - "172.16.10.60 mustafar.lan"
  - "172.16.50.30 kamino.lan"
  - "172.16.10.60 pihole3.lan"
pihole_dns_upstreams:
  - "127.0.0.1#5335"