---
- name: Installationspfad prüfen
  ansible.builtin.stat:
    path: /usr/bin/pihole-FTL
  register: pihole_install

- name: Prüfen ob Pihole installiert ist
  ansible.builtin.assert:
    that:
      - pihole_install.stat.exists
    fail_msg: "Pihole ist nicht installiert. Bitte zuerst installieren."

- name: Pihole-FTL service starten
  ansible.builtin.systemd:
    name: pihole-FTL.service
    state: started
    enabled: true
  tags: [pihole-service]
